### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by mattwthompson** [Psivant/stormm#1]
I found something that looks like an MIT license in the source tree, but I'm not sure if that applies to only those files or the entire project - might it make more sense to add a LICENSE file at the root of the repository?

https://github.com/Psivant/stormm/blob/main/src/copyright.h

**Comment by DaveCerutti** [comment]
Good idea!  Yes, the MIT license is intended to apply to the entire code base, so I will include a file for the root of the repository in my private development branch and get this into the alpha soon.

**Comment by DaveCerutti** [comment]
So long in replying... lots has been happening in my private STORMM repo (paper now accepted in JCP and more groundwork for periodic dynamics... I have a good feeling about what we can do), but on this issue I'm making a symlink license.txt in the base of the repository so as to keep copyright.h a thing with obvious "C++ includes this" qualities.  Now people will be able to find the license either way.  Any objections or other ideas, please let me know.  I tend to stick my head in algorithms without too much consideration for the legalese, but we'll get this right.

**Comment by DaveCerutti** [comment]
This evening's update adds a lot of improvements, including the license file.  Much remains in progress, but I can finally check off this issue.
